INSERT INTO public.exercises (name, muscle_group, category, equipment, instructions) VALUES
('Bench Press', 'Chest', 'Push', 'Barbell', 'Lie on a flat bench, grip the barbell slightly wider than shoulder-width. Lower the bar to your mid-chest, then press it back up.'),
('Incline Dumbbell Press', 'Chest', 'Push', 'Dumbbell', 'Set bench to a 30-45 degree incline. Press dumbbells upward until arms are fully extended.'),
('Overhead Press', 'Shoulders', 'Push', 'Barbell', 'Stand with feet shoulder-width apart. Press the barbell overhead until arms are fully extended.'),
('Lateral Raises', 'Shoulders', 'Push', 'Dumbbell', 'Stand with dumbbells at your sides. Raise arms outward to the sides until parallel with the floor.'),
('Triceps Pushdown', 'Triceps', 'Push', 'Cable', 'Use a rope or straight bar attachment. Push down until arms are fully extended, keeping elbows tucked in.'),
('Squat', 'Legs', 'Legs', 'Barbell', 'Place barbell on your upper back. Squat down until thighs are parallel to the floor, then stand back up.'),
('Leg Press', 'Legs', 'Legs', 'Machine', 'Sit in the leg press machine. Press the platform away until legs are extended, but do not lock knees.'),
('Romanian Deadlift', 'Hamstrings', 'Legs', 'Barbell', 'Hold barbell with overhand grip. Hinge at hips, keeping legs slightly bent, until you feel a stretch in hamstrings.'),
('Calf Raises', 'Calves', 'Legs', 'Machine', 'Stand on the edge of a step or calf raise machine. Raise heels as high as possible, then lower them below the edge.'),
('Deadlift', 'Back', 'Pull', 'Barbell', 'Stand with barbell over mid-foot. Hinge at hips, grip the bar, and stand up, extending hips and knees.'),
('Pull-Up', 'Back', 'Pull', 'Bodyweight', 'Grip the pull-up bar with an overhand grip. Pull yourself up until your chin clears the bar.'),
('Barbell Row', 'Back', 'Pull', 'Barbell', 'Hinge at hips, keeping back straight. Pull the barbell to your lower chest/upper abdomen.'),
('Lat Pulldown', 'Back', 'Pull', 'Cable', 'Sit at the lat pulldown machine. Pull the wide bar down to your upper chest.'),
('Bicep Curl', 'Biceps', 'Pull', 'Dumbbell', 'Hold dumbbells at your sides with palms facing forward. Curl weights up towards your shoulders.'),
('Hammer Curl', 'Biceps', 'Pull', 'Dumbbell', 'Hold dumbbells at your sides with palms facing each other. Curl weights up towards your shoulders.'),
('Crunch', 'Abs', 'Core', 'Bodyweight', 'Lie on your back with knees bent. Curl your torso up towards your knees, lifting your shoulder blades off the floor.'),
('Plank', 'Abs', 'Core', 'Bodyweight', 'Hold a push-up position, but resting on your forearms instead of your hands. Keep your body in a straight line.'),
('Leg Raises', 'Abs', 'Core', 'Bodyweight', 'Lie on your back or hang from a bar. Raise your legs until they are perpendicular to the floor.'),
('Treadmill', 'Cardio', 'Cardio', 'Machine', 'Run or walk on the treadmill at a steady pace or do intervals.'),
('Stationary Bike', 'Cardio', 'Cardio', 'Machine', 'Pedal on the stationary bike at a steady pace or do intervals.');
